///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace testRanorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the testRanorexRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("af18a707-e2a2-4d62-8955-77232c3e07f8")]
    public partial class testRanorexRepository : RepoGenBaseFolder
    {
        static testRanorexRepository instance = new testRanorexRepository();
        testRanorexRepositoryFolders.ExplorerAppFolder _explorer;
        testRanorexRepositoryFolders.UltraVncClient105FrAppFolder _ultravncclient105fr;

        /// <summary>
        /// Gets the singleton class instance representing the testRanorexRepository element repository.
        /// </summary>
        [RepositoryFolder("af18a707-e2a2-4d62-8955-77232c3e07f8")]
        public static testRanorexRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public testRanorexRepository() 
            : base("testRanorexRepository", "/", null, 0, false, "af18a707-e2a2-4d62-8955-77232c3e07f8", ".\\RepositoryImages\\testRanorexRepositoryaf18a707.rximgres")
        {
            _explorer = new testRanorexRepositoryFolders.ExplorerAppFolder(this);
            _ultravncclient105fr = new testRanorexRepositoryFolders.UltraVncClient105FrAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("af18a707-e2a2-4d62-8955-77232c3e07f8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("8fc9767c-0338-4c81-8d33-b300f16e9644")]
        public virtual testRanorexRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The UltraVncClient105Fr folder.
        /// </summary>
        [RepositoryFolder("aedbb999-7df1-4703-b7e9-9e33bbce1443")]
        public virtual testRanorexRepositoryFolders.UltraVncClient105FrAppFolder UltraVncClient105Fr
        {
            get { return _ultravncclient105fr; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class testRanorexRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("8fc9767c-0338-4c81-8d33-b300f16e9644")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ultravncclient105frInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "8fc9767c-0338-4c81-8d33-b300f16e9644", "")
            {
                _ultravncclient105frInfo = new RepoItemInfo(this, "UltraVncClient105Fr", "?/?/list[@controlid='1']/listitem[@text='UltraVnc-Client-105-Fr']", 30000, null, "50642f40-ffe1-4ee9-a021-a169e4be0541");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8fc9767c-0338-4c81-8d33-b300f16e9644")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8fc9767c-0338-4c81-8d33-b300f16e9644")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UltraVncClient105Fr item.
            /// </summary>
            [RepositoryItem("50642f40-ffe1-4ee9-a021-a169e4be0541")]
            public virtual Ranorex.ListItem UltraVncClient105Fr
            {
                get
                {
                    return _ultravncclient105frInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The UltraVncClient105Fr item info.
            /// </summary>
            [RepositoryItemInfo("50642f40-ffe1-4ee9-a021-a169e4be0541")]
            public virtual RepoItemInfo UltraVncClient105FrInfo
            {
                get
                {
                    return _ultravncclient105frInfo;
                }
            }
        }

        /// <summary>
        /// The UltraVncClient105FrAppFolder folder.
        /// </summary>
        [RepositoryFolder("aedbb999-7df1-4703-b7e9-9e33bbce1443")]
        public partial class UltraVncClient105FrAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fermerInfo;

            /// <summary>
            /// Creates a new UltraVncClient105Fr  folder.
            /// </summary>
            public UltraVncClient105FrAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UltraVncClient105Fr", "/form[@title='UltraVnc-Client-105-Fr']", parentFolder, 30000, null, true, "aedbb999-7df1-4703-b7e9-9e33bbce1443", "")
            {
                _fermerInfo = new RepoItemInfo(this, "Fermer", "?/?/button[@accessiblename='Fermer']", 30000, null, "e97df178-93d8-4907-9952-4fb9cd3bbcfa");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aedbb999-7df1-4703-b7e9-9e33bbce1443")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aedbb999-7df1-4703-b7e9-9e33bbce1443")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Fermer item.
            /// </summary>
            [RepositoryItem("e97df178-93d8-4907-9952-4fb9cd3bbcfa")]
            public virtual Ranorex.Button Fermer
            {
                get
                {
                    return _fermerInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Fermer item info.
            /// </summary>
            [RepositoryItemInfo("e97df178-93d8-4907-9952-4fb9cd3bbcfa")]
            public virtual RepoItemInfo FermerInfo
            {
                get
                {
                    return _fermerInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}